### ISSUE TITLE
누가 커밋한거야.....잘못했잔아....!!!!! 콘솔에 찍으면 안되는데.........!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by micosara** [micosara/test#1]
커밋 : 3a6650ce1042d8d613bd4bff46a010d9d33045d5

이거말이야...누가한거냐꾸~!!!!

반성해라...다시해야해~~!!!!

**Comment by sw5934** [comment]
죄송합니다 ㅠㅠ
